### ISSUE TITLE
I seem to have problem with hget binary image jpeg from redis

### ISSUE THREAD

**Issue by hwongcom** [ptrofimov/tinyredisclient#1]
Sometimes it returns 8192 length of binary data
other times it returns 16384 length of binary data

can you help? i think it's something to do with reading binary data or socket timeout or something?

**Comment by ptrofimov** [comment]
Try to set timeout here https://github.com/ptrofimov/tinyredisclient/blob/master/src/TinyRedisClient.php#L43 (arg number 4)
