### ISSUE TITLE
I would like to have array of tinyredisclient

### ISSUE THREAD

**Issue by hwongcom** [ptrofimov/tinyredisclient#2]
e.g. as in predis

$array = new Predis_Client(array(
                        array('host' => '127.0.0.1','port' => 1000),
                        array('host' => '127.0.0.1','port' => 1001),
                        array('host' => '127.0.0.1','port' => 1002),
                        array('host' => '127.0.0.1','port' => 1003),
                        array('host' => '127.0.0.1','port' => 1004)
                        ));

how can i make this...

$config = '127.0.0.1:1000';
$item = new TinyRedisClient($config);

to 

$config = array('127.0.0.1:1000','127.0.0.1:1001','127.0.0.1:1002');
$item = new TinyRedisClient($config);

this php will be complete and excellent if this feature is added. please help. thanks.

**Comment by ptrofimov** [comment]
TinyRedisClient supports only one connection. Supporting of many connections is much more complicated task.

**Comment by hwongcom** [comment]
it's ok. i worked around. it's great piece of work! thanks
