### ISSUE TITLE
How do you use multi and exec with tinyredisclient?

### ISSUE THREAD

**Issue by hwongcom** [ptrofimov/tinyredisclient#3]
How do you use multi and exec with tinyredisclient? Do you have an example usage?

I've tried the multi and exec... it "works" but i think i need to call the connection too many times...

e.g. 
$redis->multi();
$redis->scard('a');
$redis->scard('b');
.
.
$redis->scard('z');

$values=$redis->exec();
but... it doesn't seem to send everything all at once?

**Comment by hwongcom** [comment]
what i mean it is making 38 trips to redis instead of 1.

**Comment by ptrofimov** [comment]
As I know, all requests that you send, they are not executed immediately by Redis. They are stored in buffer and executed only when you call "exec"
